project:
  type: website
  output-dir: _site

website:
  title: "Numerical Methods for Energy, Thermal, and Fluid Engineering"
  site-url: https://vlc1.github.io/ene-4302a/
  navbar:
    left:
      - text: "Chapters"
        menu:
          - href: chapters/chapter1.qmd
            text: "1. Introduction"
          - href: chapters/chapter2.qmd
            text: "2. Initial Value Problems"
          - href: chapters/chapter3.qmd
            text: "3. Boundary Value Problems"
          - href: chapters/chapter4.qmd
            text: "4. Elliptic and Parabolic Problems"
          - href: chapters/chapter5.qmd
            text: "5. Numerical Solution of Algebraic Systems"
      - text: "Problem Sets"
        menu:
          - href: problem-sets/ps1.qmd
            text: "Problem Set 1"
          - href: problem-sets/ps2.qmd
            text: "Problem Set 2"
          - href: problem-sets/ps3.qmd
            text: "Problem Set 3"
  page-footer:
    left: "© 2026 Gustave Eiffel University. This work is licensed under [CC BY NC ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0)"
    right: "Part of [Vincent Le Chenadec's courses](https://vlc1.github.io/courses/)"

execute:
  freeze: auto

julia:
  project: "."

format:
  html:
    theme:
      - cosmo
      - custom-theme.scss
    css: styles.css
    toc: true
    page-layout: article
    title-block-banner: false
    anchor-sections: true



